console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = false

[palette]
black = '#262B44'
blue = '#4B95E9'
green = '#59C9A5'
orange = '#F07623'
red = '#D81E5B'
white = '#E0DEF4'
yellow = '#F3AE35'

[secondary_prompt]
background = "transparent"
foreground = "#ffffff"
template = "-> "

[transient_prompt]

style = 'plain'
foreground = 'lightCyan'
template = '❯ '

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false












[[blocks]]
type = 'prompt'
alignment = 'left'

newline = true

[[blocks.segments]]
type = "os"
style = "diamond"
foreground = "black"
background = "lightCyan"
template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}}"
leading_diamond = ''

[[blocks.segments]]
trailing_diamond = ''
template = ' {{ if .SSHSession }} {{ end }}{{ .Env.myPoshUser }}'
foreground = 'black'
background = 'lightCyan'
type = 'session'
style = 'diamond'

[[blocks.segments]]
template = '  {{ .PWD }} '
foreground = 'black'
trailing_diamond = ''
background = 'cyan'
type = 'path'
style = 'diamond'

[blocks.segments.properties]
style = 'folder'

[[blocks.segments]]
template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
foreground = 'p:black'
background = 'p:green'
type = 'git'
style = 'diamond'
trailing_diamond = ''
foreground_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}',
  '{{ if gt .Ahead 0 }}black{{ end }}',
]
background_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}',
  '{{ if gt .Ahead 0 }}#8857e6{{ end }}',
  '{{ if gt .Behind 0 }}#7A306C{{ end }}',
]

[blocks.segments.properties]
branch_template = '{{ trunc 25 .Branch }}'
fetch_status = true
fetch_upstream_icon = true


# Pride flag strips
[[blocks.segments]]
trailing_diamond = ''
template = '{{ if eq .Env.PRIDE "0" }}{{ else }}{{ if eq .Env.TERM_PROGRAM "vscode" }} {{ else }} ​{{ end }}{{ end }}'
foreground = 'black'
background = '#0038A8'
type = 'session'
style = 'diamond'

[[blocks.segments]]
trailing_diamond = ''
template = '{{ if eq .Env.PRIDE "0" }}{{ else }}{{ if eq .Env.TERM_PROGRAM "vscode" }} {{ else }}​{{ end }}{{ end }}'
foreground = 'black'
background = '#9B4F96'
type = 'session'
style = 'diamond'

[[blocks.segments]]
trailing_diamond = ''
template = '{{ if eq .Env.PRIDE "0" }}{{ else }}{{ if eq .Env.TERM_PROGRAM "vscode" }} {{ else }} {{ end }}{{ end }}'
foreground = 'black'
background = '#D60270'
type = 'session'
style = 'diamond'















[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
template = ' {{ .FormattedMs }} '
foreground = 'p:white'
background = 'transparent'
type = 'executiontime'
style = 'powerline'

[[blocks.segments]]
template = '{{ .CurrentDate | date "15:04:05" }} '
foreground = 'p:white'
background = 'transparent'
type = 'time'
style = 'plain'

[[blocks]]
newline = true
type = 'prompt'
alignment = 'left'
[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}red{{ else }}lightCyan{{ end }}']
template = ''

[[blocks]]
type = 'prompt'
alignment = 'left'
[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = 'lightCyan'
template = '❯'
